# ============================================================
# MODULE: config_gen.py
# Covers: Generate Configuration (#34), Functions (#11),
#         Strings (#1), Variables (#5), Lists (#8),
#         Dictionary (#7), For-loops (#2),
#         Lambda (#15), Advanced Functions (#14)
# ============================================================

from typing import List, Dict, Any


def generate_base_config(device: dict) -> str:
    """
    Generate full base configuration for a device.
    Covers: Config Gen (#34), Strings (#1), Variables (#5)
    """
    name      = device["name"]                               # Variables (#5)
    iface     = device["interface"]
    ip        = device["ip_address"]
    mask      = device["subnet_mask"]
    loop_ip   = device["loopback_ip"]
    loop_mask = device["loopback_mask"]
    username  = device["username"]
    password  = device["password"]

    # Multi-line string with f-string interpolation (#1)
    config = f"""
! ============================================================
! BASE CONFIGURATION FOR {name}
! Generated by Python Network Automation
! ============================================================
version 15.2
service timestamps debug datetime msec
service timestamps log datetime msec
!
hostname {name}
!
aaa new-model
!
username {username} privilege 15 secret {password}
!
ip domain-name lab.local
!
interface {iface}
 ip address {ip} {mask}
 no shutdown
 description LINK_TO_PEER
!
interface Loopback0
 ip address {loop_ip} {loop_mask}
 no shutdown
 description LOOPBACK_{name}
!
line con 0
 logging synchronous
line vty 0 4
 login local
 transport input ssh telnet
!
crypto key generate rsa modulus 1024
ip ssh version 2
!
end
"""
    return config.strip()


def generate_bgp_config(device: dict) -> str:
    """
    Generate BGP config block.
    Covers: Config Gen (#34), Strings (#1), Variables (#5)
    """
    my_as      = device["bgp_as"]
    router_id  = device["loopback_ip"]
    neighbor   = device["bgp_neighbor"]
    neighbor_as= device["bgp_neighbor_as"]
    network    = device["ip_address"]
    netmask    = device["subnet_mask"]
    loop_ip    = device["loopback_ip"]

    bgp = f"""
router bgp {my_as}
 bgp router-id {router_id}
 bgp log-neighbor-changes
 neighbor {neighbor} remote-as {neighbor_as}
 !
 address-family ipv4
  network {network} mask {netmask}
  network {loop_ip} mask 255.255.255.255
  neighbor {neighbor} activate
 exit-address-family
"""
    return bgp.strip()


def generate_acl_config(acl_cfg: dict) -> str:
    """
    Generate an extended ACL config block.
    Covers: Config Gen (#34), For-loops (#2), Conditional (#12)
    """
    lines = [f"ip access-list extended {acl_cfg['name']}"]  # Lists (#8)

    for rule in acl_cfg["rules"]:                           # For-loops (#2)
        seq   = rule["sequence"]
        action= rule["action"]
        proto = rule["protocol"]
        src   = rule["source"]
        dst   = rule["destination"]

        if "dest_port" in rule:                             # Conditional (#12)
            line = f" {seq} {action} {proto} {src} {dst} eq {rule['dest_port']}"
        else:
            line = f" {seq} {action} {proto} {src} {dst}"

        lines.append(line)

    return "\n".join(lines)                                  # Strings (#1)


def generate_all_configs(devices: List[dict],
                         acl_cfg: dict,
                         dhcp_cfg: dict) -> Dict[str, str]:
    """
    Generate configs for all devices and return as a dictionary.
    Covers: Advanced Functions (#14), Dictionary (#7),
            For-loops (#2), Lambda (#15)
    """
    configs: Dict[str, str] = {}                             # Dictionary (#7)

    # Lambda to combine config sections
    combine = lambda *parts: "\n!\n".join(parts)             # Lambda (#15)

    for device in devices:                                   # For-loops (#2)
        base = generate_base_config(device)
        bgp  = generate_bgp_config(device)
        acl  = generate_acl_config(acl_cfg)

        # Build DHCP only for R2 (first device)
        if device["name"] == "R2":                           # Conditional (#12)
            dhcp = generate_dhcp_config(dhcp_cfg)
            full = combine(base, bgp, acl, dhcp)
        else:
            full = combine(base, bgp, acl)

        configs[device["name"]] = full                       # Dictionary (#7)
        print(f"    [CFG] Generated config for {device['name']} ({len(full)} chars)")

    return configs


def generate_dhcp_config(dhcp_cfg: dict) -> str:
    """Generate DHCP pool config."""
    return f"""
ip dhcp excluded-address {dhcp_cfg['default_router']}
!
ip dhcp pool {dhcp_cfg['pool_name']}
 network {dhcp_cfg['network']} {dhcp_cfg['mask']}
 default-router {dhcp_cfg['default_router']}
 dns-server {dhcp_cfg['dns_server']}
 lease {dhcp_cfg['lease_days']}
""".strip()


def save_config_to_file(name: str, config: str, out_dir: str = "reports") -> None:
    """Save a config string to file."""
    import os
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{name}_config.txt")
    with open(path, "w") as f:
        f.write(config)
    print(f"    [CFG] Saved: {path}")
